#!/bin/bash

cols=$(tput cols)
rows=$(tput lines)

if [ "$cols" -lt 80 ] || [ "$rows" -lt 40 ]; then
    echo "Oops, in order to have the best gaming experience please use a terminal size of at least 80x40 and try again!"
else
    cd ./src
    python3 main.py
    cd ..
fi
